name: backend-ci

on:
  push:
    paths: ["backend/**", ".github/workflows/backend.yml"]
  pull_request:
    paths: ["backend/**", ".github/workflows/backend.yml"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: backend/requirements-dev.txt

      - name: Install deps
        working-directory: backend
        run: pip install -r requirements-dev.txt

      - name: Lint (Ruff)
        working-directory: backend
        run: ruff check .

      - name: Format check (Black)
        working-directory: backend
        run: black --check --diff .

      - name: Tests
        working-directory: backend
        env:
          PYTHONPATH: ${{ github.workspace }}/backend
        run: pytest -q
