name: backend-ci

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend   # all `run:` steps happen in /backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: backend/requirements-dev.txt

      - name: Install deps
        run: pip install -r requirements-dev.txt

      - name: Lint (Ruff)
        run: ruff check .

      - name: Format check (Black)
        run: black --check .

      - name: Type check (Mypy)  # optional, remove if not ready
        run: mypy .

      - name: Tests
        run: pytest -q
